ESSA TENTAVIVA ENVIADA FOI CRIADA PARA VISUALIZAR A POSIBILIDADE DE UMA SUGESTÃO DE DADOS COM BASE NO HISTÓRICO DA BASE SENDO DESCONTINUADA PELO FATO DE JÁ HAVER UMA FÓRMULA NA BASE ASSIM E PELO FATO DE QUE PRECISARIAMOS CRIAR A NOSSA PRÓPRIA O QUE NESSE CASO FICA INVIÁVEL PELA FALTA DE CONHECIMENTO!
A SEGUIR TEMOS TODO O ROTEIRO DE ANALISE DA BASE ASSIM BASTANDO APENAS REPETIR E ADAPTAR EM ANÁLISES FUTURAS

## IMPORTAÇÕES

In [ ]:
#Importações
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics
from sklearn.metrics import r2_score
import pyodbc
import pandas as pd
server = 'DESKTOP-BAGV6SU\\SQLEXPRESS0' 
database = 'TESTE' 
username = ''
password = '' 
cnxn = pyodbc.connect('DRIVER={SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
cursor = cnxn.cursor()
print("foi")

### CRIANDO O DATAFRAME COLETADO DA BASE SQL SERVER

In [3]:
cursor = cnxn.cursor()
resultado = pd.read_sql(" select * from RESULTADOS_ANTERIORES$  " , cnxn)
resultado = resultado.drop("ID_RESULTADO", axis = 1)
display(resultado)
cnxn.commit()
cursor.close()

,NUMERO1,NUMERO2,NUMERO3,NUMERO4,NUMERO5,NUMERO6,NUMERO7,NUMERO8,NUMERO9,NUMERO10,NUMERO11,NUMERO12,NUMERO13,NUMERO14,NUMERO15,NUMERO16,NUMERO17,NUMERO18,NUMERO19,NUMERO20
0,6.0,11.0,14.0,16.0,21.0,22.0,25.0,32.0,33.0,34.0,46.0,61.0,70.0,73.0,78.0,88.0,89.0,90.0,95.0,100.0
1,8.0,11.0,14.0,17.0,18.0,24.0,29.0,37.0,44.0,49.0,51.0,55.0,62.0,63.0,64.0,76.0,82.0,84.0,93.0,97.0
2,8.0,10.0,11.0,17.0,20.0,22.0,28.0,34.0,45.0,47.0,48.0,54.0,55.0,57.0,67.0,74.0,79.0,85.0,91.0,99.0
3,5.0,12.0,14.0,25.0,30.0,35.0,39.0,41.0,44.0,49.0,51.0,55.0,60.0,63.0,64.0,67.0,78.0,83.0,93.0,98.0
4,8.0,17.0,20.0,28.0,32.0,39.0,42.0,43.0,51.0,54.0,59.0,65.0,69.0,71.0,73.0,87.0,92.0,98.0,99.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2302,4.0,12.0,24.0,25.0,29.0,30.0,34.0,40.0,56.0,60.0,67.0,69.0,72.0,74.0,83.0,88.0,94.0,97.0,98.0,99.0
2303,3.0,5.0,8.0,11.0,28.0,30.0,37.0,38.0,40.0,42.0,46.0,51.0,61.0,63.0,65.0,75.0,86.0,90.0,92.0,94.0
2304,2.0,4.0,7.0,12.0,17.0,19.0,33.0,40.0,43.0,44.0,46.0,48.0,52.0,63.0,67.0,71.0,72.0,85.0,95.0,96.0
2305,7.0,10.0,14.0,24.0,28.0,32.0,33.0,36.0,40.0,53.0,56.0,60.0,68.0,73.0,79.0,80.0,81.0,93.0,95.0,98.0
2306,6.0,18.0,19.0,23.0,31.0,40.0,51.0,53.0,54.0,64.0,69.0,74.0,79.0,84.0,88.0,92.0,95.0,96.0,97.0,99.0

### TREINANDO AS IAs

In [5]:
#treino das IAs
x = resultado
y = resultado
#acerto_linear = 0.0
#acerto_random = 0.0
#erro_li = 10.0
#erro_ra = 10.0
#a = 0.000011
#quantidade = 0.0
#for i in range(1):

x_treino, x_teste,y_treino , y_teste =  train_test_split(x,y,random_state = 19 ,test_size = 0.1100109999999806)#0.006
linear = LinearRegression()
randomforest = RandomForestRegressor()
linear.fit(x_treino,y_treino)
randomforest.fit(x_treino,y_treino)
teste_linear = linear.predict(x_teste)
teste_random = randomforest.predict(x_teste) 
r2_linear = r2_score(y_teste, teste_linear)
r2_random = r2_score(y_teste, teste_random)
erro_linear = metrics.mean_squared_error(y_teste, teste_linear)
erro_random = metrics.mean_squared_error(y_teste, teste_random)
    #if erro_linear< erro_li:
        #erro_li = erro_linear
        #ia_linear =teste_linear
        #quantidade = a
    #if erro_random < erro_ra:
        #erro_ra = erro_random
        #ia_random = teste_random
        #quantidade = a
print(r2_linear,r2_random)
#print(erro_li, erro_ra)
print(erro_linear, erro_random)

1.0 0.8489072072072095
6.464425676795715e-28 7.404330059055118

### ESCOLHENDO A IA

In [6]:
# separa a base de dados 
# ALTERAÇÃO  NA QUANTIDADE NECESSÁRIA PARA ANALISAR OUTROS TIPOS DE BASES
x = resultado
y = resultado[NUMERO1]
# treino
x_treino,x_teste,y_treino, y_teste=train_test_split(x,y,random_state =0,test_size = 0.1100109999999806)#
linear = LinearRegression()
linear.fit(x_treino,y_treino)
teste_linear = linear.predict(x_teste)
# pontuação
r2_linear = r2_score(y_teste, teste_linear)
erro_linear = metrics.mean_squared_error(y_teste, teste_linear)
print(r2_linear)
print(erro_linear)

1.0
4.3335693179636375e-27

### TESTANDO A IA

In [7]:
tabela_linear = pd.DataFrame(teste_linear)
#tabela_comparacao = pd.DataFrame(teste_random)
print("linear")
display(tabela_linear)
display(x_teste)
#print("forest")
#display(tabela_comparacao)
#display(x_teste)

linear

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,8.0,12.0,23.0,26.0,34.0,45.0,48.0,51.0,52.0,62.0,66.0,68.0,69.0,71.0,77.0,82.0,86.0,92.0,94.0,100.0
1,6.0,18.0,19.0,23.0,31.0,40.0,51.0,53.0,54.0,64.0,69.0,74.0,79.0,84.0,88.0,92.0,95.0,96.0,97.0,99.0
2,1.0,4.0,8.0,14.0,17.0,19.0,27.0,35.0,36.0,39.0,41.0,44.0,59.0,64.0,66.0,68.0,70.0,77.0,89.0,93.0
3,9.0,12.0,13.0,18.0,22.0,32.0,34.0,41.0,51.0,53.0,56.0,66.0,70.0,80.0,82.0,85.0,94.0,95.0,98.0,99.0
4,2.0,17.0,24.0,25.0,27.0,35.0,38.0,39.0,42.0,43.0,46.0,48.0,57.0,58.0,61.0,70.0,77.0,81.0,89.0,99.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,9.0,25.0,30.0,33.0,35.0,40.0,44.0,49.0,56.0,57.0,62.0,66.0,68.0,72.0,78.0,81.0,82.0,85.0,89.0,91.0
250,4.0,10.0,11.0,13.0,17.0,18.0,21.0,26.0,30.0,31.0,37.0,44.0,54.0,55.0,57.0,70.0,72.0,74.0,82.0,100.0
251,2.0,13.0,17.0,39.0,45.0,47.0,49.0,53.0,60.0,63.0,64.0,74.0,78.0,83.0,86.0,89.0,90.0,91.0,92.0,100.0
252,1.0,2.0,3.0,6.0,12.0,21.0,31.0,35.0,46.0,47.0,48.0,50.0,51.0,52.0,59.0,64.0,69.0,71.0,89.0,100.0
253,2.0,10.0,12.0,16.0,20.0,31.0,40.0,43.0,47.0,48.0,50.0,51.0,54.0,61.0,63.0,67.0,75.0,86.0,91.0,98.0

,NUMERO1,NUMERO2,NUMERO3,NUMERO4,NUMERO5,NUMERO6,NUMERO7,NUMERO8,NUMERO9,NUMERO10,NUMERO11,NUMERO12,NUMERO13,NUMERO14,NUMERO15,NUMERO16,NUMERO17,NUMERO18,NUMERO19,NUMERO20
124,8.0,12.0,23.0,26.0,34.0,45.0,48.0,51.0,52.0,62.0,66.0,68.0,69.0,71.0,77.0,82.0,86.0,92.0,94.0,100.0
2306,6.0,18.0,19.0,23.0,31.0,40.0,51.0,53.0,54.0,64.0,69.0,74.0,79.0,84.0,88.0,92.0,95.0,96.0,97.0,99.0
1428,1.0,4.0,8.0,14.0,17.0,19.0,27.0,35.0,36.0,39.0,41.0,44.0,59.0,64.0,66.0,68.0,70.0,77.0,89.0,93.0
1964,9.0,12.0,13.0,18.0,22.0,32.0,34.0,41.0,51.0,53.0,56.0,66.0,70.0,80.0,82.0,85.0,94.0,95.0,98.0,99.0
1727,2.0,17.0,24.0,25.0,27.0,35.0,38.0,39.0,42.0,43.0,46.0,48.0,57.0,58.0,61.0,70.0,77.0,81.0,89.0,99.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1702,9.0,25.0,30.0,33.0,35.0,40.0,44.0,49.0,56.0,57.0,62.0,66.0,68.0,72.0,78.0,81.0,82.0,85.0,89.0,91.0
1788,4.0,10.0,11.0,13.0,17.0,18.0,21.0,26.0,30.0,31.0,37.0,44.0,54.0,55.0,57.0,70.0,72.0,74.0,82.0,100.0
1029,2.0,13.0,17.0,39.0,45.0,47.0,49.0,53.0,60.0,63.0,64.0,74.0,78.0,83.0,86.0,89.0,90.0,91.0,92.0,100.0
578,1.0,2.0,3.0,6.0,12.0,21.0,31.0,35.0,46.0,47.0,48.0,50.0,51.0,52.0,59.0,64.0,69.0,71.0,89.0,100.0
333,2.0,10.0,12.0,16.0,20.0,31.0,40.0,43.0,47.0,48.0,50.0,51.0,54.0,61.0,63.0,67.0,75.0,86.0,91.0,98.0